### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/dress-for-the-weather#1]
Hi @LornaLynch & @LornaLynch,

Could I get another copyedit please. Thanks

**Comment by lauraclay** [comment]
All done :+1:

**Comment by MarcScott** [comment]
Awesome - thanks @LornaLynch

**Comment by LornaLynch** [comment]
Thanks @lauraclay! Sorry Marc: I've been dealing with Ronan's 2nd birthday today...
