### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Georgielaa** [raspberrypilearning/dress-for-the-weather#13]
Hey, I'm having difficulty with this tutorial and I suspect that the possible reason is that the format of the 'city.list.json' may have changed. Iv'e opened the 'city.list.json' file on my PC and it seems that it is formatted in some sort of an array, but i'm not experienced enough to do any re-formatting or conversion with it.
After running the weather.py file and entering the following into the shell:-
>>>cities = open('city.list.json').readlines()
>>>cities[0]

I get the following result:-
>>>'[\n'

And if i enter:-
>>>cities[1]

I get the following result:-
>>>'   {\n'

And if i enter:-
>>>cities[2]

I get the  following result:-
>>>'      "id": 707860, \n"

After doing all that and then entering:-
>>>city = loads(cities[56325])

Well it just totally spits out the dummy then!
PLS see the attached image for a screenshot.
Thanks,
George
![ashampoo_snap_2018 09 11_16h00m14s_001_georgepi3bench -georgepi3bench- - vnc viewer](https://user-images.githubusercontent.com/26186850/45368685-14ba8200-b5dc-11e8-98cc-ce56cdafe8fe.jpg)

**Comment by Georgielaa** [comment]
Actually iv'e just looked at the 'city.list.json' that you have in this repo and it is structured very differently than the one you get as a download, from clicking the link on the https://projects.raspberrypi.org/en/projects/dress-for-the-weather/5 webpage.

**Comment by hchowd** [comment]
same issue. please help asap!

**Comment by hchowd** [comment]
@MarcScott please help! i tried everything that i could but i'm getting the above errors too

**Comment by MarcScott** [comment]
The json format has changed from OWM.
I think this should now be fixed.
Changed the opening of the file to be
```python
with open('city.list.json') as f:
        data = loads(f.read())
```
and removed the `_` from `_id` key look up.
Please reopen if there are further issues @hchowd and @Georgielaa
