### ISSUE TITLE
i have the same issue as above.

### ISSUE THREAD

**Issue by hchowd** [raspberrypilearning/dress-for-the-weather#15]
1. pprint(forecast) is returning none
2. File "weather.py", line 48, in get_readable_forecast
weather['cloudiness'] = forecast['clouds']['all']
TypeError: 'NoneType' object is not subscriptable

please help

_Originally posted by @hchowd in https://github.com/raspberrypilearning/dress-for-the-weather/issues/7#issuecomment-430078623_

**Comment by MarcScott** [comment]
Should now be fixed - new version of project published
