### ISSUE TITLE
401 Open weather api key 

### ISSUE THREAD

**Issue by dlaweb** [raspberrypilearning/dress-for-the-weather#29]
Hi i've recentyle discovered the tutorial :
https://projects.raspberrypi.org/en/projects/dress-for-the-weather/4

But i've some trouble with the api key. Maybe they've restricted the usage : 
pyowm.exceptions.api_response_error.UnauthorizedError: Your API subscription level does not allow to perform this operation

**Comment by libxx1** [comment]
Closing issue as this is being investigated more widely under #31
