### ISSUE TITLE
API no longer free (Apr 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/dress-for-the-weather#30]
A couple of users noted that the API daily_forecast call no longer a free API

**Comment by libxx1** [comment]
A further comment about the daily_forecast. Can this be looked into at the same time please

"Hi there, I'm not certain that the command:
forecast = owm.daily_forecast(location + ',' + COUNTRY)
...still works with OpenWeatherMaps, I've only had success when using the following:
url = "https://api.openweathermap.org/data/2.5/onecall?lat=%s&lon=%s&appid=%s&units=metric" % (lat, lon, api_key)

It would be useful to see any dates when the article was written, so for instance, if it's a recent article then I'm probably wrong, but if the article was from 2017/18/19 then perhaps the tutorial needs to be reviewed."

**Comment by libxx1** [comment]
Closing this issue as #31 is a duplicate with more information.

**Comment by MarcScott** [comment]
Archived this resource, due to API changes
