### ISSUE TITLE
get_readable_forecast

### ISSUE THREAD

**Issue by ghost** [raspberrypilearning/dress-for-the-weather#7]
When selecting an hour that results in a single digit hour I get the message:
File "weather.py", line 48, in get_readable_forecast
    weather['cloudiness'] = forecast['clouds']['all']
TypeError: 'NoneType' object is not subscriptable

I can fix this by padding - str(hour).rjust(2,'0')

I presume this will need to be done for the day also.

**Comment by MarcScott** [comment]
I'm going to rewrite this resource to use the new Weather API functionality in Scratch 1.4 on the Raspberry Pi - see #10

**Comment by hchowd** [comment]
i have the same issue as above.
1. pprint(forecast) is returning none
2. File "weather.py", line 48, in get_readable_forecast
weather['cloudiness'] = forecast['clouds']['all']
TypeError: 'NoneType' object is not subscriptable

please help

**Comment by mastansberry** [comment]
I get the same thing.  please help
