### ISSUE TITLE
closed string before end of string

### ISSUE THREAD

**Issue by TeCoEd** [raspberrypilearning/dress-for-the-weather#8]
Hi Mark, Tried this last night and line 4 produces an error as the ' is picked up between you and re and program treats this as the end of the string.

def get_city_id():
    with open('city.list.json') as f:
        data = [loads(line) for line in f]
    city = input('Which is the closest city to the place you're travelling to?' )
    city_id = False

**Comment by LornaLynch** [comment]
Thanks: I'm working on correcting this now.

**Comment by bennuttall** [comment]
The easiest fix is to use double quotes! Here's a round-up of some options for dealing with strings containing quotes:

``` python
s = 'Hello I'm Ben'  # broken
s = "Hello I'm Ben"  # works
s = 'Hello I\'m Ben'  # also works but unnecessary (backslash escapes quote character)
s = "Hello I'm Ben and I say "hello""  # broken
s = "Hello I'm Ben and I say \"hello\""  # works, backslashes more necessary
s = 'Hello I\'m Ben and I say "hello"'  # works, alternative to above
```

**Comment by LornaLynch** [comment]
Thanks Ben! I'm just correcting it to "you are" from "you're" as it's a very straightforward fix, but I'll bear this in mind for the future.

**Comment by LornaLynch** [comment]
@bennuttall, @MarcScott Following on from this, I was checking the rest of the code for apostrophes, and I noticed there might be some issues with the "get clothes" section of the code: some of the print statements have single inverted commas and some have double. I assume I need to change these all to double, but wanted to check before jumping in. I can also add escape characters if necessary.

**Comment by MarcScott** [comment]
I'll do a quick code review
